const EVENT = {
    FETCH: 'EVENT_FETCH',
    FETCH_ERROR: 'EVENT_FETCH_ERROR',
    FETCH_SUCCESS: 'EVENT_FETCH_SUCCESS'
};

const TICKET = {
    FETCH: 'TICKET_FETCH',
    FETCH_ERROR: 'TICKET_FETCH_ERROR',
    FETCH_SUCCESS: 'TICKET_FETCH_SUCCESS'
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_TICKETS = {
    FETCH: 'ACCOUNT_TICKET_FETCH',
    FETCH_ERROR: 'ACCOUNT_TICKET_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_TICKET_FETCH_SUCCESS'
};

export { EVENT, TICKET, ACCOUNT, ACCOUNT_TICKETS };